// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vuelos.API.Data;

#nullable disable

namespace Vuelos.API.Migrations
{
    [DbContext(typeof(VuelosContext))]
    [Migration("20251215205553_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vuelos.Shared.Aeropuerto", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Aeropuertos");

                    b.HasData(
                        new
                        {
                            Codigo = "MAD",
                            Ciudad = "Madrid",
                            Nombre = "Adolfo Suárez"
                        },
                        new
                        {
                            Codigo = "BCN",
                            Ciudad = "Barcelona",
                            Nombre = "El Prat"
                        },
                        new
                        {
                            Codigo = "JFK",
                            Ciudad = "New York",
                            Nombre = "John F. Kennedy"
                        },
                        new
                        {
                            Codigo = "LHR",
                            Ciudad = "Londres",
                            Nombre = "Heathrow"
                        },
                        new
                        {
                            Codigo = "CDG",
                            Ciudad = "París",
                            Nombre = "Charles de Gaulle"
                        },
                        new
                        {
                            Codigo = "DXB",
                            Ciudad = "Dubai",
                            Nombre = "Dubai Intl"
                        },
                        new
                        {
                            Codigo = "HND",
                            Ciudad = "Tokio",
                            Nombre = "Haneda"
                        },
                        new
                        {
                            Codigo = "SYD",
                            Ciudad = "Sydney",
                            Nombre = "Kingsford Smith"
                        });
                });

            modelBuilder.Entity("Vuelos.Shared.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("AsientosReservados")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ImportePagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombrePasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VueloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VueloId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Vuelos.Shared.Vuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AsientosOcupados")
                        .HasColumnType("int");

                    b.Property<int>("AsientosTotales")
                        .HasColumnType("int");

                    b.Property<string>("DestinoCodigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigenCodigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DestinoCodigo");

                    b.HasIndex("OrigenCodigo");

                    b.ToTable("Vuelos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            AsientosOcupados = 120,
                            AsientosTotales = 150,
                            DestinoCodigo = "BCN",
                            Fecha = new DateTime(2025, 12, 16, 21, 55, 53, 687, DateTimeKind.Local).AddTicks(1993),
                            Hora = "08:00",
                            OrigenCodigo = "MAD",
                            Precio = 55m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            AsientosOcupados = 40,
                            AsientosTotales = 150,
                            DestinoCodigo = "MAD",
                            Fecha = new DateTime(2025, 12, 17, 2, 55, 53, 687, DateTimeKind.Local).AddTicks(2042),
                            Hora = "13:00",
                            OrigenCodigo = "BCN",
                            Precio = 60m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            AsientosOcupados = 299,
                            AsientosTotales = 300,
                            DestinoCodigo = "JFK",
                            Fecha = new DateTime(2025, 12, 17, 21, 55, 53, 687, DateTimeKind.Local).AddTicks(2045),
                            Hora = "10:30",
                            OrigenCodigo = "MAD",
                            Precio = 450m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            AsientosOcupados = 150,
                            AsientosTotales = 300,
                            DestinoCodigo = "LHR",
                            Fecha = new DateTime(2025, 12, 18, 21, 55, 53, 687, DateTimeKind.Local).AddTicks(2047),
                            Hora = "18:00",
                            OrigenCodigo = "JFK",
                            Precio = 380m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            AsientosOcupados = 300,
                            AsientosTotales = 300,
                            DestinoCodigo = "JFK",
                            Fecha = new DateTime(2025, 12, 19, 21, 55, 53, 687, DateTimeKind.Local).AddTicks(2049),
                            Hora = "09:15",
                            OrigenCodigo = "LHR",
                            Precio = 410m
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            AsientosOcupados = 10,
                            AsientosTotales = 180,
                            DestinoCodigo = "MAD",
                            Fecha = new DateTime(2025, 12, 16, 21, 55, 53, 687, DateTimeKind.Local).AddTicks(2051),
                            Hora = "07:45",
                            OrigenCodigo = "CDG",
                            Precio = 90m
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            AsientosOcupados = 90,
                            AsientosTotales = 180,
                            DestinoCodigo = "LHR",
                            Fecha = new DateTime(2025, 12, 20, 21, 55, 53, 687, DateTimeKind.Local).AddTicks(2053),
                            Hora = "16:20",
                            OrigenCodigo = "MAD",
                            Precio = 120m
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            AsientosOcupados = 200,
                            AsientosTotales = 400,
                            DestinoCodigo = "HND",
                            Fecha = new DateTime(2025, 12, 25, 21, 55, 53, 687, DateTimeKind.Local).AddTicks(2055),
                            Hora = "02:00",
                            OrigenCodigo = "DXB",
                            Precio = 850m
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            AsientosOcupados = 50,
                            AsientosTotales = 350,
                            DestinoCodigo = "SYD",
                            Fecha = new DateTime(2025, 12, 26, 21, 55, 53, 687, DateTimeKind.Local).AddTicks(2057),
                            Hora = "22:30",
                            OrigenCodigo = "HND",
                            Precio = 700m
                        },
                        new
                        {
                            Id = 10,
                            Activo = false,
                            AsientosOcupados = 0,
                            AsientosTotales = 100,
                            DestinoCodigo = "JFK",
                            Fecha = new DateTime(2025, 12, 14, 21, 55, 53, 687, DateTimeKind.Local).AddTicks(2058),
                            Hora = "12:00",
                            OrigenCodigo = "MAD",
                            Precio = 0m
                        });
                });

            modelBuilder.Entity("Vuelos.Shared.Reserva", b =>
                {
                    b.HasOne("Vuelos.Shared.Vuelo", "Vuelo")
                        .WithMany()
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("Vuelos.Shared.Vuelo", b =>
                {
                    b.HasOne("Vuelos.Shared.Aeropuerto", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vuelos.Shared.Aeropuerto", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Origen");
                });
#pragma warning restore 612, 618
        }
    }
}
