// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vuelos.API.Data;

#nullable disable

namespace Vuelos.API.Migrations
{
    [DbContext(typeof(VuelosContext))]
    [Migration("20251215174352_InicioLimpio")]
    partial class InicioLimpio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vuelos.Shared.Aeropuerto", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Aeropuertos");

                    b.HasData(
                        new
                        {
                            Codigo = "MAD",
                            Ciudad = "Madrid",
                            Nombre = "Barajas"
                        },
                        new
                        {
                            Codigo = "BCN",
                            Ciudad = "Barcelona",
                            Nombre = "El Prat"
                        },
                        new
                        {
                            Codigo = "JFK",
                            Ciudad = "New York",
                            Nombre = "JFK Intl"
                        });
                });

            modelBuilder.Entity("Vuelos.Shared.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("AsientosReservados")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ImportePagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombrePasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VueloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Vuelos.Shared.Vuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsientosOcupados")
                        .HasColumnType("int");

                    b.Property<int>("AsientosTotales")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Vuelos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AsientosOcupados = 10,
                            AsientosTotales = 100,
                            Destino = "BCN",
                            Fecha = new DateTime(2025, 12, 16, 18, 43, 52, 790, DateTimeKind.Local).AddTicks(3431),
                            Hora = "",
                            Origen = "MAD",
                            Precio = 50m
                        },
                        new
                        {
                            Id = 2,
                            AsientosOcupados = 199,
                            AsientosTotales = 200,
                            Destino = "JFK",
                            Fecha = new DateTime(2025, 12, 17, 18, 43, 52, 790, DateTimeKind.Local).AddTicks(3475),
                            Hora = "",
                            Origen = "MAD",
                            Precio = 450m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
